Katharopoulos2020transformers kelseyball
395t/review-assignments pull request #100
Opened 2021-09-30 22:04 UTC by kelseyball

Hey Sai, my summary is ready for review. Sorry for the delay.

2021-10-01 04:42 UTC, saikm200022 commented on _summaries/katharopoulos2020transformers_1.md
> +Expressing self-attention using kernel feature maps can reduce its time and space complexity from quadratic to linear
Another core component to their paper was re-expressing their transformer model as a RNN to achieve much greater inference speeds.

2021-10-01 05:31 UTC, saikm200022 requested changes
Great, concise summary! I have some suggestions that I believe can improve your summary.

2021-10-01 05:31 UTC, saikm200022 commented on _summaries/katharopoulos2020transformers_1.md
> +- However, the authors show that part of the attention computation at each timestep can be computed iteratively. In other words, it can be computed in constant time using the previous value. This obs
I think you should bring up these two points for some context. With autoregressive transformers, it is easier to parallelize during training and not possible during test time. The attention computation must also be repeated for previous time steps.

2021-10-01 05:31 UTC, saikm200022 commented on _summaries/katharopoulos2020transformers_1.md
> +- However, the authors show that part of the attention computation at each timestep can be computed iteratively. In other words, it can be computed in constant time using the previous value. This obs
I would be a little bit more specific when you are talking about what part of the attention computation that is being stored and updated as internal state: phi (K_j ) V^T

2021-10-01 05:31 UTC, saikm200022 commented on _summaries/katharopoulos2020transformers_1.md
> +- **Synthetic experiments:** They train autoregressive transformers for an artificial copy task. They show that computation and memory scales linearly with linear transformer and reformer, and quadra
The paper has 2 graphs that are side-by-side of time and GPU memory usage vs. Sequence Length for the different architectures tested. Adding that image will bolster your summary of the synthetic experiments.

2021-10-01 05:31 UTC, saikm200022 commented on _summaries/katharopoulos2020transformers_1.md
> +# Experiments
I would mention somewhere in the Experiments section that despite performing much faster, "Linear Transformers" attained the same final performance as the traditional softmax transformer.

2021-10-01 05:31 UTC, saikm200022 commented on _summaries/katharopoulos2020transformers_1.md
> +- **Image generation:** They use autoregressive transformers to generate CIFAR-10 images pixel by pixel. Linear transformer generates images 4000x times faster than transformer with softmax attention
Including table 2 from the paper can also provide some perspective on how the other methods performed on this particular task.

2021-10-04 17:12 UTC, zhaoyue-zephyrus approved these changes

2021-10-04 17:12 UTC, merged