Yin2020center based 1 marcobueso
395t/review-assignments pull request #182
Opened 2021-10-28 19:40 UTC by marcobueso

Hi @SShivang, ready for initial review! I apologize for submitting a bit late.

2021-10-31 03:27 UTC, SShivang requested changes

2021-10-31 03:27 UTC, SShivang commented on _summaries/yin2020center-based_1.md
> +Initial ablation study was center-based v. anchor-based methods. As mentioned above, center-based performs better.\
Maybe you could include the figure from the paper regarding the ablation, and discuss the results of the ablation.

2021-10-31 03:27 UTC, SShivang commented on _summaries/yin2020center-based_1.md
> +
I think you can also add why this method works better than previous works.

2021-10-31 03:27 UTC, SShivang commented on _summaries/yin2020center-based_1.md
> +CenterPoint uses a standard Lidar-based backbone network, (VoxelNet or PointPillars), to build a representation of the input point-cloud. It flattens the point-cloud and maps the center of the object
Good explanation.

2021-10-31 03:27 UTC, SShivang commented on _summaries/yin2020center-based_1.md
> +Authors also show that center-based methods for 3D detection, like CenterPoint, outperform anchor-based methods.
Again, could mention why they outperform. What is the factor that the other models didn't have?

2021-11-01 00:58 UTC, marcobueso commented
Comments addressed and ready for submission.

2021-11-01 16:01 UTC, zhaoyue-zephyrus approved these changes

2021-11-01 16:01 UTC, merged