Wu2021rethinking 2
395t/review-assignments pull request #92
Opened 2021-09-30 02:45 UTC by aabayomi

2021-10-01 21:35 UTC, DartingMelody requested changes
Hi, Your summary has the essential points but it is somewhat difficult to follow. Can you please explain a bit more and have a flow in the summary. That will improve your summary a lot. Let me know if you have any doubts or need any help.

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +
Can you also add how the paper changes attention computation for quadratic time complexity to linear time complexity?

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +
The paper also discusses on why non-negative kernels are useful. Can you please add that?

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +
Also, can you add that paper introduced Performer which uses linear space and complexity without depending on priors like low-rankness or sparsity? Also can you talk a bit about FAVOR+.

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +Well known method to reduce the variance of the estimator  by selecting random features and orthogonal random samples.
It's kind of difficult to follow this line, maybe you can give some context.  Also, add about the representational power of FAVOR+ on large scale tasks.

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +FAVOR+(Performer) = ORFs + PSFs
PSFs - can you add the full form and also a one-line explanation of this line here.

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +Baseline comparison  of FAVOR+ (Performer) with normal Transformer models for both unidirectional/causal modeling and bidirectional/masked language modeling tasks
Is this the caption of the previous image ?

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +Orthogonal features show lower softmax attention approximation error. Also using positive features produced lower errors compared to $sine/cosine$ features.
You missed $sine/cosine$  to $$sine/cosine$$

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +Showed backward compatibility with pre-trained models benefitting from softmax approximation.
Did you mean performers displayed backward compatibility with pre-trained models benefitting from softmax approximation.

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +Performer showed better training performance on ImageNet64 dataset.
in comparison to which models (Are you referring to Reformer, Linformer)

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +* Transformers requires a huge cost of computation but Performer are more efficient.
you can also add peformer uses FAVOR+ provides time and space-efficient approximation of attention.

2021-10-01 21:35 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +
Another point could be performers are fully compatible with Transfomer and provide strong theoretical guarantees, without any priors.

2021-10-01 21:57 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +
Will you be explaining this, while presenting or else you can replace this picture with more content on why non-negative kernel scores are useful. How they have technically reduced the time complexity of attention from O(L^2 * D) to O(Lrd). Also maybe add just the required math expressions.

2021-10-01 21:57 UTC, DartingMelody commented on _summaries/wu2021rethinking_2.md
> +FAVOR+(Performer) = ORFs + PSFs
And also explain the algorithm below in short.

2021-10-04 04:52 UTC, aabayomi commented
Thank you, I have made the reviewed changes. let me know if there is anything else missing.

2021-10-04 22:20 UTC, zhaoyue-zephyrus commented
@aabayomi could you do me a favor by removing changes on `reddi2019_1` and rename all `wu2021rethinking_XX`s to `choromanski2021rethinking_XX` otherwise there are conflicts with previous reviews.

2021-10-05 06:12 UTC, aabayomi commented
> @aabayomi could you do me a favor by removing changes on `reddi2019_1` and rename all `wu2021rethinking_XX`s to `choromanski2021rethinking_XX` otherwise there are conflicts with previous reviews? You can open a new PR if you want.

2021-10-05 06:26 UTC, aabayomi commented
@zhaoyue-zephyrus  sorry for this conflict by removing do you mean delete?

2021-10-05 06:36 UTC, zhaoyue-zephyrus commented
@aabayomi you can start from the latest main branch, checkout a new branch, and add only `choromanski2021rethinking_2`-related files in it, and initiate a new PR.

2021-10-05 18:58 UTC, zhaoyue-zephyrus commented
closing this because of a newer PR #109

2021-10-05 18:58 UTC, closed without merging